### ISSUE TITLE
serve_model doesn't terminate children

### ISSUE THREAD

**Issue by chrispan68** [eth-sri/lmql#13]
I'm using

`serve_model_process = subprocess.Popen(["python" , "-m" "lmql.model.serve", args.model, "--cuda"])`

to serve a model in the background of a python script. However, when I call `serve_model_process.terminate()` it doesn't properly terminate the process. When I look into ps, I see there are actually multiple processes running that are serving the model. 

Is there a better way to terminate the subprocess that serves the model in python or is this an issue with the termination logic?

(Love this repo by the way, thanks so much for everyone's hard work 💯 )

**Comment by chrispan68** [comment]
If it's an issue with the LMQL codebase I'd be more than happy to look into it, and submit a PR?

**Comment by lbeurerkellner** [comment]
Will this be fixed in https://github.com/eth-sri/lmql/pull/15 or is it a separate issue?

**Comment by chrispan68** [comment]
#15 doesn't fix this issue, I can look into this and submit a separate PR in the near future.

**Comment by praveenv** [comment]
@chrispan68 Do you mind sharing a code snippet of how you implement `subprocess` for the model serving and the client calls? I've tried using the flag that you added in #15 , but am probably doing something wrong. 
An example would be much appreciated!

**Comment by chrispan68** [comment]
In here, I spawn a model process and terminate it when the evaluation script terminates.

**Comment by chrispan68** [comment]
Let me know if this isn't relevant. Good luck!

**Comment by praveenv** [comment]
Thank you so much!! 
A followup question -- 
What does `lmql_model_server_running()` do?
Do you keep checking if `port 8080` can be connected to? I was trying to do that using the `socket` library

**Comment by lbeurerkellner** [comment]
Since the latest serve-model implemented no longer relies on multiprocessing and child processes, this issue should be fixed with the latest version.
